
---
- name: Configure nginx web server
  hosts: webservers
  become: True
  tasks:
  - name: install nginx server 
    apt: 
      name: nginx
      state: latest
  - name: start nginx server 
    service: 
      name: nginx
      state: started 